# Generated by Django 5.2.9 on 2025-12-20 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('content_html', models.TextField(help_text='Formatted HTML report')),
                ('content_text', models.TextField(help_text='Plain text version of report')),
                ('commit_count', models.IntegerField(default=0)),
                ('repo_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='core.report')),
            ],
            options={
                'db_table': 'delivery_log',
            },
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_token', models.CharField(help_text='GitHub personal access token', max_length=255)),
                ('github_username', models.CharField(help_text='GitHub username', max_length=255)),
                ('email', models.EmailField(help_text='Email to receive daily reports', max_length=254)),
                ('report_time', models.TimeField(default='18:00', help_text='Time to send daily report (HH:MM)')),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_config',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='user_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.userconfig'),
        ),
        migrations.CreateModel(
            name='GithubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(help_text='Repo name (e.g., owner/repo)', max_length=255)),
                ('repo_url', models.URLField()),
                ('is_monitored', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='core.userconfig')),
            ],
            options={
                'db_table': 'github_repository',
                'unique_together': {('user_config', 'repo_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('user_config', 'report_date')},
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('files_changed', models.IntegerField(default=0)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('commit_date', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='core.githubrepository')),
                ('user_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='core.userconfig')),
            ],
            options={
                'db_table': 'commit',
                'indexes': [models.Index(fields=['user_config', 'commit_date'], name='commit_user_co_5149c1_idx'), models.Index(fields=['is_processed', 'commit_date'], name='commit_is_proc_778360_idx')],
            },
        ),
    ]
